document.addEventListener("DOMContentLoaded", function () {
  // Traduzioni complete per Email Campaign Manager
  const translations = {
    en: {
      kb_nav_title: "Sections",
      kb_nav_intro: "Introduction",
      kb_nav_quickstart: "Quick Start",
      kb_nav_campaigns: "Campaign Manager",
      kb_nav_templates: "Templates",
      kb_nav_abtesting: "A/B Testing",
      kb_nav_scheduling: "Scheduling",
      kb_nav_contacts: "Import Contacts",
      kb_nav_smtp: "SMTP Setup",
      kb_nav_compose: "Compose Message",
      kb_nav_send: "Send Campaign",
      kb_nav_security: "Security",
      kb_nav_troubleshooting: "Troubleshooting",
      kb_nav_support: "Support",
      kb_title: "Email Campaign Manager Knowledge Base",
      kb_intro_title: "Introduction",
      kb_intro_desc: "Email Campaign Manager v1.4 is a powerful desktop application for sending beautiful, personalized email campaigns. Manage campaigns, schedule sends, run A/B tests, and use advanced templates - all in one professional tool!",
      kb_features_title: "Key Features",
      kb_template_engine_title: "🎨 Template Engine (v1.4)",
      kb_feature_template_vars: "Advanced variables with Jinja2 syntax",
      kb_feature_template_conditions: "Conditional content support",
      kb_feature_template_library: "Template library for reuse",
      kb_feature_template_preview: "Real-time preview with CSV data",
      kb_feature_template_validation: "Syntax validation",
      kb_abtesting_title: "🧪 A/B Testing (v1.3)",
      kb_feature_ab_split: "Custom split ratios",
      kb_feature_ab_variants: "Different subjects and content",
      kb_feature_ab_preview: "Side-by-side variant preview",
      kb_feature_ab_tracking: "Separate tracking for variants",
      kb_scheduling_title: "⏰ Scheduling & Throttling (v1.2)",
      kb_feature_schedule: "Schedule campaigns for future delivery",
      kb_feature_timezone: "Timezone support (UTC, CET, EST, PST, JST, AEST)",
      kb_feature_ratelimit: "Rate limiting (0-60 emails/min)",
      kb_feature_pause: "Pause/Resume campaigns",
      kb_feature_resume: "Auto-resume after crashes",
      kb_campaigns_title: "📊 Campaign Manager (v1.1)",
      kb_feature_organize: "Organize with names, tags, and notes",
      kb_feature_status: "Track status (Draft, Scheduled, Sent)",
      kb_feature_search: "Search and filter campaigns",
      kb_feature_duplicate: "Duplicate successful campaigns",
      kb_quickstart_title: "Quick Start",
      kb_quickstart_desc: "Get started in minutes with these simple steps:",
      kb_quickstart_step1: "Place EmailCampaignManager.exe in any folder and double-click it",
      kb_quickstart_step2: "Your browser opens at http://localhost:5000 automatically",
      kb_quickstart_step3: "Allow through your antivirus if prompted (PyInstaller apps can trigger false positives)",
      kb_quickstart_step4: "Configure your SMTP settings",
      kb_quickstart_step5: "Import your contacts CSV",
      kb_quickstart_step6: "Create your first campaign and send!",
      kb_campaigns_section_title: "Campaign Manager",
      kb_campaigns_desc: "Manage all your email campaigns in one organized place.",
      kb_campaigns_create_title: "Create a Campaign",
      kb_campaigns_create_step1: "Click the Campaigns tab",
      kb_campaigns_create_step2: "Click ➕ New Campaign",
      kb_campaigns_create_step3: "Compose your email in the Compose tab",
      kb_campaigns_create_step4: "Click ⚙️ Settings to set name, tags, and notes",
      kb_campaigns_create_step5: "Click 💾 Save to save your progress",
      kb_campaigns_manage_title: "Manage Campaigns",
      kb_campaigns_search: "Search: Type in the search box to find campaigns",
      kb_campaigns_filter: "Filter: Click Draft/Scheduled/Sent to filter by status",
      kb_campaigns_edit: "Edit: Click on a campaign card to open and edit it",
      kb_campaigns_actions: "Actions: Click ⋮ for Duplicate or Delete options",
      kb_campaigns_send_title: "Send a Campaign",
      kb_campaigns_send_step1: "Select or create a campaign",
      kb_campaigns_send_step2: "Load your CSV file with recipients",
      kb_campaigns_send_step3: "Configure SMTP settings",
      kb_campaigns_send_step4: "Click 🚀 Send Emails",
      kb_campaigns_send_step5: "Statistics update automatically!",
      kb_templates_section_title: "Using Templates",
      kb_templates_desc: "Create powerful, reusable email templates with variables and conditional content.",
      kb_templates_create_title: "Create a Template",
      kb_templates_create_step1: "Click the Templates tab",
      kb_templates_create_step2: "Click ➕ New Template",
      kb_templates_create_step3: "Enter template name and description",
      kb_templates_create_step4: "Write your email using variables and conditions",
      kb_templates_create_step5: "Select a category (promo, newsletter, cold, follow-up)",
      kb_templates_create_step6: "Click 💾 Save Template",
      kb_templates_use_title: "Use a Template",
      kb_templates_use_step1: "In the Compose tab, click 📄 Load Template",
      kb_templates_use_step2: "Select a template from the library",
      kb_templates_use_step3: "The subject and body are automatically filled",
      kb_templates_use_step4: "Variables will be replaced with real data from your CSV",
      kb_templates_syntax_title: "Template Syntax",
      kb_templates_syntax_vars: "Variables: Use any column from your CSV with {{column_name}}",
      kb_templates_syntax_conditions: "Conditions: Show/hide content based on data",
      kb_templates_syntax_preview: "Preview: Click the preview button to see how it renders with sample data",
      kb_abtesting_section_title: "Running A/B Tests",
      kb_abtesting_desc: "Test different email variations to find what works best for your audience.",
      kb_abtesting_setup_title: "Set Up an A/B Test",
      kb_abtesting_setup_step1: "Create or edit a campaign",
      kb_abtesting_setup_step2: "Click ⚙️ Settings",
      kb_abtesting_setup_step3: "Enable A/B Test Mode",
      kb_abtesting_setup_step4: "Set your split ratio (default 50/50)",
      kb_abtesting_setup_step5: "Go to Compose tab",
      kb_abtesting_setup_step6: "Enter Variant A subject and body",
      kb_abtesting_setup_step7: "Enter Variant B subject and body",
      kb_abtesting_setup_step8: "Click 👁️ Preview to compare side-by-side",
      kb_abtesting_send_title: "Send A/B Test",
      kb_abtesting_send_step1: "Load your CSV with recipients",
      kb_abtesting_send_step2: "Configure SMTP settings",
      kb_abtesting_send_step3: "Click 🚀 Send A/B Test",
      kb_abtesting_send_step4: "Recipients are automatically split (e.g., 50% get A, 50% get B)",
      kb_abtesting_send_step5: "View separate statistics for each variant",
      kb_scheduling_section_title: "Scheduling Campaigns",
      kb_scheduling_desc: "Schedule campaigns for future delivery and control sending speed.",
      kb_scheduling_schedule_title: "Schedule for Later",
      kb_scheduling_schedule_step1: "Create or edit a campaign",
      kb_scheduling_schedule_step2: "Click ⚙️ Settings",
      kb_scheduling_schedule_step3: "Set Scheduled Date & Time",
      kb_scheduling_schedule_step4: "Select your Timezone",
      kb_scheduling_schedule_step5: "Click 💾 Save",
      kb_scheduling_schedule_step6: "Campaign shows ⏰ badge and will send automatically",
      kb_scheduling_ratelimit_title: "Control Send Rate",
      kb_scheduling_ratelimit_step1: "In Campaign Settings, adjust Emails per Minute slider",
      kb_scheduling_ratelimit_step2: "Set to 0 for maximum speed (no limit)",
      kb_scheduling_ratelimit_step3: "Set to 1-60 to control delivery rate",
      kb_scheduling_ratelimit_step4: "Helps improve deliverability and avoid rate limits",
      kb_scheduling_pause_title: "Pause & Resume",
      kb_scheduling_pause_step1: "During sending, click ⏸️ Pause if needed",
      kb_scheduling_pause_step2: "Campaign state is saved automatically",
      kb_scheduling_pause_step3: "Click ▶️ Resume to continue from where it stopped",
      kb_scheduling_pause_step4: "If app crashes, campaigns auto-resume on restart",
      kb_contacts_title: "Import Your Contacts",
      kb_contacts_desc: "Use the bundled TemplateCSV.csv as your starting point.",
      kb_contacts_format_title: "CSV Format",
      kb_contacts_headers: "Required headers (exactly): Name,Email separated by commas",
      kb_contacts_encoding: "Save as UTF-8 encoding",
      kb_contacts_example_title: "Example",
      kb_contacts_empty_note: "Leave Name empty if you don't have it (the default greeting will be used)",
      kb_smtp_title: "Connect Your Email Account",
      kb_smtp_desc: "Configure your SMTP settings to send emails.",
      kb_smtp_providers_title: "Supported Providers",
      kb_smtp_gmail: "Gmail (use App Password with 2FA enabled)",
      kb_smtp_outlook: "Outlook/Hotmail",
      kb_smtp_yahoo: "Yahoo",
      kb_smtp_office365: "Office 365",
      kb_smtp_custom: "Custom SMTP (any provider)",
      kb_smtp_setup_title: "Setup Steps",
      kb_smtp_step1: "Pick your provider from the dropdown",
      kb_smtp_step2: "Enter your email and password (or app password)",
      kb_smtp_step3: "Click Test Connection",
      kb_smtp_step4: "On success, your password is stored securely in the system keychain",
      kb_smtp_step5: "Use the dropdown to recall saved accounts",
      kb_compose_title: "Craft Your Message",
      kb_compose_desc: "Create personalized emails with variables and templates.",
      kb_compose_basics_title: "Basics",
      kb_compose_subject: "Subject is required",
      kb_compose_mode: "Switch between Text and HTML modes in the editor",
      kb_compose_attachments: "Add shared attachments with Load Files",
      kb_compose_variables_title: "Using Variables",
      kb_compose_jinja: "Jinja2 syntax: {{first_name}}, {{email}}, {{company}}, or any CSV column",
      kb_compose_legacy: "Legacy syntax: {name} and {email} still supported",
      kb_compose_conditions: "Conditions: {% if company %}at {{company}}{% endif %} shows content only if field exists",
      kb_compose_default: "If Name is missing, the Default Greeting is used (e.g., \"Dear Friend\")",
      kb_compose_templates_title: "Load Templates",
      kb_compose_templates_desc: "Click 📄 Load Template from the Templates tab to reuse your best messages.",
      kb_send_title: "Send Your Campaign",
      kb_send_desc: "Send your email campaign and track progress in real-time.",
      kb_send_steps_title: "Steps",
      kb_send_step1: "Press 🚀 Send Emails",
      kb_send_step2: "Watch live logs, progress bar, and stats while the campaign runs",
      kb_send_step3: "Campaign status updates automatically",
      kb_send_monitoring_title: "Monitoring",
      kb_send_progress: "Real-time progress bar",
      kb_send_logs: "Live logs showing each email sent",
      kb_send_stats: "Success/error statistics",
      kb_send_pause_option: "Option to pause during sending",
      kb_security_title: "Security",
      kb_security_desc: "Your data and credentials are protected.",
      kb_security_features_title: "Security Features",
      kb_security_keychain: "Passwords stored locally in system keychain (Windows Credential Manager)",
      kb_security_local: "All data stays on your computer - no cloud storage",
      kb_security_sqlite: "SQLite database for campaign storage",
      kb_security_remove_title: "Remove Credentials",
      kb_security_remove_desc: "To remove stored credentials: select the account and click Cancel Account.",
      kb_troubleshooting_title: "Troubleshooting",
      kb_troubleshooting_common_title: "Common Issues",
      kb_trouble_smtp_title: "SMTP Connection Failed",
      kb_trouble_smtp_1: "Use an App Password (Gmail requires 2FA + App Password)",
      kb_trouble_smtp_2: "Verify host/port for Custom SMTP",
      kb_trouble_smtp_3: "Check your internet connection",
      kb_trouble_csv_title: "CSV Rejected",
      kb_trouble_csv_1: "Headers must be exactly Name,Email",
      kb_trouble_csv_2: "Use comma separator (no semicolons)",
      kb_trouble_csv_3: "Save as UTF-8 encoding",
      kb_trouble_attachments_title: "Attachments Corrupted",
      kb_trouble_attachments_1: "All file types supported (PDF, DOCX, images, etc.)",
      kb_trouble_attachments_2: "Files are encoded as base64 automatically",
      kb_trouble_attachments_3: "Check recipient's email client settings",
      kb_trouble_icon_title: "Windows Icon Looks Old",
      kb_trouble_icon_desc: "Delete or rename the old EmailCampaignManager.exe and copy the new one (Windows may cache icons).",
      kb_support_title: "Support & Contact",
      kb_support_desc: "Need help, have questions, or just want to say hi? 😊",
      kb_support_contact_title: "Get in Touch",
      kb_support_contact_desc: "Click the button below to contact me:",
      kb_support_contact_btn: "Contact Me"
    },
    de: {
      kb_nav_title: "Abschnitte",
      kb_nav_intro: "Einführung",
      kb_nav_quickstart: "Schnellstart",
      kb_nav_campaigns: "Kampagnenmanager",
      kb_nav_templates: "Vorlagen",
      kb_nav_abtesting: "A/B-Tests",
      kb_nav_scheduling: "Planung",
      kb_nav_contacts: "Kontakte importieren",
      kb_nav_smtp: "SMTP-Einrichtung",
      kb_nav_compose: "Nachricht verfassen",
      kb_nav_send: "Kampagne senden",
      kb_nav_security: "Sicherheit",
      kb_nav_troubleshooting: "Fehlerbehebung",
      kb_nav_support: "Support",
      kb_title: "Email Campaign Manager Knowledge Base",
      kb_intro_title: "Einführung",
      kb_intro_desc: "Email Campaign Manager v1.4 ist eine leistungsstarke Desktop-Anwendung zum Versenden schöner, personalisierter E-Mail-Kampagnen. Verwalten Sie Kampagnen, planen Sie Versendungen, führen Sie A/B-Tests durch und nutzen Sie erweiterte Vorlagen - alles in einem professionellen Tool!",
      kb_features_title: "Hauptfunktionen",
      kb_template_engine_title: "🎨 Vorlagen-Engine (v1.4)",
      kb_feature_template_vars: "Erweiterte Variablen mit Jinja2-Syntax",
      kb_feature_template_conditions: "Unterstützung bedingter Inhalte",
      kb_feature_template_library: "Vorlagenbibliothek zur Wiederverwendung",
      kb_feature_template_preview: "Echtzeit-Vorschau mit CSV-Daten",
      kb_feature_template_validation: "Syntax-Validierung",
      kb_abtesting_title: "🧪 A/B-Tests (v1.3)",
      kb_feature_ab_split: "Benutzerdefinierte Aufteilungsverhältnisse",
      kb_feature_ab_variants: "Unterschiedliche Betreffzeilen und Inhalte",
      kb_feature_ab_preview: "Nebeneinander-Variantenvorschau",
      kb_feature_ab_tracking: "Separate Verfolgung für Varianten",
      kb_scheduling_title: "⏰ Planung & Drosselung (v1.2)",
      kb_feature_schedule: "Planen Sie Kampagnen für zukünftige Zustellung",
      kb_feature_timezone: "Zeitzonenunterstützung (UTC, CET, EST, PST, JST, AEST)",
      kb_feature_ratelimit: "Ratenbegrenzung (0-60 E-Mails/Min)",
      kb_feature_pause: "Kampagnen pausieren/fortsetzen",
      kb_feature_resume: "Automatische Wiederaufnahme nach Abstürzen",
      kb_campaigns_title: "📊 Kampagnenmanager (v1.1)",
      kb_feature_organize: "Organisieren mit Namen, Tags und Notizen",
      kb_feature_status: "Status verfolgen (Entwurf, Geplant, Gesendet)",
      kb_feature_search: "Kampagnen suchen und filtern",
      kb_feature_duplicate: "Erfolgreiche Kampagnen duplizieren",
      kb_quickstart_title: "Schnellstart",
      kb_quickstart_desc: "Beginnen Sie in wenigen Minuten mit diesen einfachen Schritten:",
      kb_quickstart_step1: "Platzieren Sie EmailCampaignManager.exe in einem beliebigen Ordner und doppelklicken Sie darauf",
      kb_quickstart_step2: "Ihr Browser öffnet sich automatisch unter http://localhost:5000",
      kb_quickstart_step3: "Erlauben Sie es in Ihrem Antivirenprogramm, wenn Sie dazu aufgefordert werden (PyInstaller-Apps können Fehlalarme auslösen)",
      kb_quickstart_step4: "Konfigurieren Sie Ihre SMTP-Einstellungen",
      kb_quickstart_step5: "Importieren Sie Ihre Kontakte-CSV",
      kb_quickstart_step6: "Erstellen Sie Ihre erste Kampagne und senden Sie sie!",
      kb_campaigns_section_title: "Kampagnenmanager",
      kb_campaigns_desc: "Verwalten Sie alle Ihre E-Mail-Kampagnen an einem organisierten Ort.",
      kb_campaigns_create_title: "Kampagne erstellen",
      kb_campaigns_create_step1: "Klicken Sie auf die Registerkarte Kampagnen",
      kb_campaigns_create_step2: "Klicken Sie auf ➕ Neue Kampagne",
      kb_campaigns_create_step3: "Verfassen Sie Ihre E-Mail in der Registerkarte Verfassen",
      kb_campaigns_create_step4: "Klicken Sie auf ⚙️ Einstellungen, um Name, Tags und Notizen festzulegen",
      kb_campaigns_create_step5: "Klicken Sie auf 💾 Speichern, um Ihren Fortschritt zu sichern",
      kb_campaigns_manage_title: "Kampagnen verwalten",
      kb_campaigns_search: "Suchen: Geben Sie Text in das Suchfeld ein, um Kampagnen zu finden",
      kb_campaigns_filter: "Filtern: Klicken Sie auf Entwurf/Geplant/Gesendet, um nach Status zu filtern",
      kb_campaigns_edit: "Bearbeiten: Klicken Sie auf eine Kampagnenkarte, um sie zu öffnen und zu bearbeiten",
      kb_campaigns_actions: "Aktionen: Klicken Sie auf ⋮ für Duplizieren- oder Löschen-Optionen",
      kb_campaigns_send_title: "Kampagne senden",
      kb_campaigns_send_step1: "Wählen oder erstellen Sie eine Kampagne",
      kb_campaigns_send_step2: "Laden Sie Ihre CSV-Datei mit Empfängern",
      kb_campaigns_send_step3: "SMTP-Einstellungen konfigurieren",
      kb_campaigns_send_step4: "Klicken Sie auf 🚀 E-Mails senden",
      kb_campaigns_send_step5: "Statistiken werden automatisch aktualisiert!",
      kb_templates_section_title: "Vorlagen verwenden",
      kb_templates_desc: "Erstellen Sie leistungsstarke, wiederverwendbare E-Mail-Vorlagen mit Variablen und bedingten Inhalten.",
      kb_templates_create_title: "Vorlage erstellen",
      kb_templates_create_step1: "Klicken Sie auf die Registerkarte Vorlagen",
      kb_templates_create_step2: "Klicken Sie auf ➕ Neue Vorlage",
      kb_templates_create_step3: "Geben Sie Vorlagenname und Beschreibung ein",
      kb_templates_create_step4: "Schreiben Sie Ihre E-Mail mit Variablen und Bedingungen",
      kb_templates_create_step5: "Wählen Sie eine Kategorie (Promo, Newsletter, Cold, Follow-up)",
      kb_templates_create_step6: "Klicken Sie auf 💾 Vorlage speichern",
      kb_templates_use_title: "Vorlage verwenden",
      kb_templates_use_step1: "Klicken Sie in der Registerkarte Verfassen auf 📄 Vorlage laden",
      kb_templates_use_step2: "Wählen Sie eine Vorlage aus der Bibliothek",
      kb_templates_use_step3: "Betreff und Text werden automatisch ausgefüllt",
      kb_templates_use_step4: "Variablen werden durch echte Daten aus Ihrer CSV ersetzt",
      kb_templates_syntax_title: "Vorlagensyntax",
      kb_templates_syntax_vars: "Variablen: Verwenden Sie eine beliebige Spalte aus Ihrer CSV mit {{spaltenname}}",
      kb_templates_syntax_conditions: "Bedingungen: Inhalte basierend auf Daten ein-/ausblenden",
      kb_templates_syntax_preview: "Vorschau: Klicken Sie auf die Vorschau-Schaltfläche, um zu sehen, wie sie mit Beispieldaten gerendert wird",
      kb_abtesting_section_title: "A/B-Tests durchführen",
      kb_abtesting_desc: "Testen Sie verschiedene E-Mail-Varianten, um herauszufinden, was für Ihr Publikum am besten funktioniert.",
      kb_abtesting_setup_title: "A/B-Test einrichten",
      kb_abtesting_setup_step1: "Kampagne erstellen oder bearbeiten",
      kb_abtesting_setup_step2: "Klicken Sie auf ⚙️ Einstellungen",
      kb_abtesting_setup_step3: "Aktivieren Sie den A/B-Testmodus",
      kb_abtesting_setup_step4: "Legen Sie Ihr Aufteilungsverhältnis fest (Standard 50/50)",
      kb_abtesting_setup_step5: "Gehen Sie zur Registerkarte Verfassen",
      kb_abtesting_setup_step6: "Geben Sie Betreff und Text für Variante A ein",
      kb_abtesting_setup_step7: "Geben Sie Betreff und Text für Variante B ein",
      kb_abtesting_setup_step8: "Klicken Sie auf 👁️ Vorschau, um sie nebeneinander zu vergleichen",
      kb_abtesting_send_title: "A/B-Test senden",
      kb_abtesting_send_step1: "Laden Sie Ihre CSV mit Empfängern",
      kb_abtesting_send_step2: "SMTP-Einstellungen konfigurieren",
      kb_abtesting_send_step3: "Klicken Sie auf 🚀 A/B-Test senden",
      kb_abtesting_send_step4: "Empfänger werden automatisch aufgeteilt (z.B. 50% erhalten A, 50% erhalten B)",
      kb_abtesting_send_step5: "Separate Statistiken für jede Variante anzeigen",
      kb_scheduling_section_title: "Kampagnen planen",
      kb_scheduling_desc: "Planen Sie Kampagnen für zukünftige Zustellung und steuern Sie die Sendegeschwindigkeit.",
      kb_scheduling_schedule_title: "Für später planen",
      kb_scheduling_schedule_step1: "Kampagne erstellen oder bearbeiten",
      kb_scheduling_schedule_step2: "Klicken Sie auf ⚙️ Einstellungen",
      kb_scheduling_schedule_step3: "Legen Sie geplantes Datum und Uhrzeit fest",
      kb_scheduling_schedule_step4: "Wählen Sie Ihre Zeitzone",
      kb_scheduling_schedule_step5: "Klicken Sie auf 💾 Speichern",
      kb_scheduling_schedule_step6: "Kampagne zeigt ⏰-Symbol und wird automatisch gesendet",
      kb_scheduling_ratelimit_title: "Senderate steuern",
      kb_scheduling_ratelimit_step1: "Passen Sie in den Kampagneneinstellungen den Regler E-Mails pro Minute an",
      kb_scheduling_ratelimit_step2: "Auf 0 setzen für maximale Geschwindigkeit (keine Begrenzung)",
      kb_scheduling_ratelimit_step3: "Auf 1-60 setzen, um die Zustellrate zu steuern",
      kb_scheduling_ratelimit_step4: "Hilft, die Zustellbarkeit zu verbessern und Ratenlimits zu vermeiden",
      kb_scheduling_pause_title: "Pausieren & Fortsetzen",
      kb_scheduling_pause_step1: "Klicken Sie während des Sendens bei Bedarf auf ⏸️ Pause",
      kb_scheduling_pause_step2: "Der Kampagnenstatus wird automatisch gespeichert",
      kb_scheduling_pause_step3: "Klicken Sie auf ▶️ Fortsetzen, um dort fortzufahren, wo sie gestoppt wurde",
      kb_scheduling_pause_step4: "Bei App-Abstürzen werden Kampagnen beim Neustart automatisch fortgesetzt",
      kb_contacts_title: "Kontakte importieren",
      kb_contacts_desc: "Verwenden Sie die mitgelieferte TemplateCSV.csv als Ausgangspunkt.",
      kb_contacts_format_title: "CSV-Format",
      kb_contacts_headers: "Erforderliche Spaltenüberschriften (genau): Name,Email getrennt durch Kommas",
      kb_contacts_encoding: "Als UTF-8-Kodierung speichern",
      kb_contacts_example_title: "Beispiel",
      kb_contacts_empty_note: "Lassen Sie Name leer, wenn Sie ihn nicht haben (die Standardbegrüßung wird verwendet)",
      kb_smtp_title: "E-Mail-Konto verbinden",
      kb_smtp_desc: "Konfigurieren Sie Ihre SMTP-Einstellungen zum Senden von E-Mails.",
      kb_smtp_providers_title: "Unterstützte Anbieter",
      kb_smtp_gmail: "Gmail (verwenden Sie App-Passwort mit aktivierter 2FA)",
      kb_smtp_outlook: "Outlook/Hotmail",
      kb_smtp_yahoo: "Yahoo",
      kb_smtp_office365: "Office 365",
      kb_smtp_custom: "Benutzerdefiniertes SMTP (beliebiger Anbieter)",
      kb_smtp_setup_title: "Einrichtungsschritte",
      kb_smtp_step1: "Wählen Sie Ihren Anbieter aus der Dropdown-Liste",
      kb_smtp_step2: "Geben Sie Ihre E-Mail und Ihr Passwort (oder App-Passwort) ein",
      kb_smtp_step3: "Klicken Sie auf Verbindung testen",
      kb_smtp_step4: "Bei Erfolg wird Ihr Passwort sicher im System-Keychain gespeichert",
      kb_smtp_step5: "Verwenden Sie die Dropdown-Liste, um gespeicherte Konten abzurufen",
      kb_compose_title: "Nachricht verfassen",
      kb_compose_desc: "Erstellen Sie personalisierte E-Mails mit Variablen und Vorlagen.",
      kb_compose_basics_title: "Grundlagen",
      kb_compose_subject: "Betreff ist erforderlich",
      kb_compose_mode: "Wechseln Sie im Editor zwischen Text- und HTML-Modus",
      kb_compose_attachments: "Fügen Sie gemeinsame Anhänge mit Dateien laden hinzu",
      kb_compose_variables_title: "Variablen verwenden",
      kb_compose_jinja: "Jinja2-Syntax: {{first_name}}, {{email}}, {{company}} oder jede CSV-Spalte",
      kb_compose_legacy: "Legacy-Syntax: {name} und {email} werden weiterhin unterstützt",
      kb_compose_conditions: "Bedingungen: {% if company %}bei {{company}}{% endif %} zeigt Inhalt nur an, wenn Feld existiert",
      kb_compose_default: "Wenn Name fehlt, wird die Standardbegrüßung verwendet (z.B. \"Lieber Freund\")",
      kb_compose_templates_title: "Vorlagen laden",
      kb_compose_templates_desc: "Klicken Sie auf 📄 Vorlage laden auf der Registerkarte Vorlagen, um Ihre besten Nachrichten wiederzuverwenden.",
      kb_send_title: "Kampagne senden",
      kb_send_desc: "Senden Sie Ihre E-Mail-Kampagne und verfolgen Sie den Fortschritt in Echtzeit.",
      kb_send_steps_title: "Schritte",
      kb_send_step1: "Drücken Sie 🚀 E-Mails senden",
      kb_send_step2: "Sehen Sie sich Live-Protokolle, Fortschrittsbalken und Statistiken an, während die Kampagne läuft",
      kb_send_step3: "Kampagnenstatus wird automatisch aktualisiert",
      kb_send_monitoring_title: "Überwachung",
      kb_send_progress: "Echtzeit-Fortschrittsbalken",
      kb_send_logs: "Live-Protokolle, die jede gesendete E-Mail zeigen",
      kb_send_stats: "Erfolgs-/Fehlerstatistiken",
      kb_send_pause_option: "Option zum Pausieren während des Sendens",
      kb_security_title: "Sicherheit",
      kb_security_desc: "Ihre Daten und Anmeldeinformationen sind geschützt.",
      kb_security_features_title: "Sicherheitsfunktionen",
      kb_security_keychain: "Passwörter lokal im System-Keychain gespeichert (Windows-Anmeldeinformationsverwaltung)",
      kb_security_local: "Alle Daten bleiben auf Ihrem Computer - keine Cloud-Speicherung",
      kb_security_sqlite: "SQLite-Datenbank für Kampagnenspeicherung",
      kb_security_remove_title: "Anmeldeinformationen entfernen",
      kb_security_remove_desc: "Um gespeicherte Anmeldeinformationen zu entfernen: Wählen Sie das Konto aus und klicken Sie auf Konto abbrechen.",
      kb_troubleshooting_title: "Fehlerbehebung",
      kb_troubleshooting_common_title: "Häufige Probleme",
      kb_trouble_smtp_title: "SMTP-Verbindung fehlgeschlagen",
      kb_trouble_smtp_1: "Verwenden Sie ein App-Passwort (Gmail erfordert 2FA + App-Passwort)",
      kb_trouble_smtp_2: "Überprüfen Sie Host/Port für benutzerdefiniertes SMTP",
      kb_trouble_smtp_3: "Überprüfen Sie Ihre Internetverbindung",
      kb_trouble_csv_title: "CSV abgelehnt",
      kb_trouble_csv_1: "Überschriften müssen genau Name,Email sein",
      kb_trouble_csv_2: "Verwenden Sie Kommatrennzeichen (keine Semikolons)",
      kb_trouble_csv_3: "Als UTF-8-Kodierung speichern",
      kb_trouble_attachments_title: "Anhänge beschädigt",
      kb_trouble_attachments_1: "Alle Dateitypen unterstützt (PDF, DOCX, Bilder usw.)",
      kb_trouble_attachments_2: "Dateien werden automatisch als base64 kodiert",
      kb_trouble_attachments_3: "Überprüfen Sie die E-Mail-Client-Einstellungen des Empfängers",
      kb_trouble_icon_title: "Windows-Symbol sieht alt aus",
      kb_trouble_icon_desc: "Löschen oder benennen Sie die alte EmailCampaignManager.exe um und kopieren Sie die neue (Windows kann Symbole zwischenspeichern).",
      kb_support_title: "Support & Kontakt",
      kb_support_desc: "Benötigen Sie Hilfe, haben Fragen oder möchten einfach nur Hallo sagen? 😊",
      kb_support_contact_title: "Kontakt aufnehmen",
      kb_support_contact_desc: "Klicken Sie auf die Schaltfläche unten, um mich zu kontaktieren:",
      kb_support_contact_btn: "Kontaktieren Sie mich"
    },
    it: {
      kb_nav_title: "Sezioni",
      kb_nav_intro: "Introduzione",
      kb_nav_quickstart: "Avvio Rapido",
      kb_nav_campaigns: "Gestione Campagne",
      kb_nav_templates: "Template",
      kb_nav_abtesting: "A/B Testing",
      kb_nav_scheduling: "Pianificazione",
      kb_nav_contacts: "Importa Contatti",
      kb_nav_smtp: "Configurazione SMTP",
      kb_nav_compose: "Componi Messaggio",
      kb_nav_send: "Invia Campagna",
      kb_nav_security: "Sicurezza",
      kb_nav_troubleshooting: "Risoluzione Problemi",
      kb_nav_support: "Supporto",
      kb_title: "Email Campaign Manager Knowledge Base",
      kb_intro_title: "Introduzione",
      kb_intro_desc: "Email Campaign Manager v1.4 è una potente applicazione desktop per inviare campagne email personalizzate e professionali. Gestisci campagne, pianifica invii, esegui test A/B e usa template avanzati - tutto in un unico strumento professionale!",
      kb_features_title: "Funzionalità Principali",
      kb_template_engine_title: "🎨 Template Engine (v1.4)",
      kb_feature_template_vars: "Variabili avanzate con sintassi Jinja2",
      kb_feature_template_conditions: "Supporto contenuto condizionale",
      kb_feature_template_library: "Libreria template riutilizzabili",
      kb_feature_template_preview: "Anteprima in tempo reale con dati CSV",
      kb_feature_template_validation: "Validazione sintassi",
      kb_abtesting_title: "🧪 A/B Testing (v1.3)",
      kb_feature_ab_split: "Rapporti di divisione personalizzati",
      kb_feature_ab_variants: "Oggetti e contenuti diversi",
      kb_feature_ab_preview: "Anteprima affiancata delle varianti",
      kb_feature_ab_tracking: "Tracciamento separato per varianti",
      kb_scheduling_title: "⏰ Pianificazione & Controllo (v1.2)",
      kb_feature_schedule: "Pianifica campagne per invio futuro",
      kb_feature_timezone: "Supporto fusi orari (UTC, CET, EST, PST, JST, AEST)",
      kb_feature_ratelimit: "Limitazione velocità (0-60 email/min)",
      kb_feature_pause: "Pausa/Riprendi campagne",
      kb_feature_resume: "Ripresa automatica dopo crash",
      kb_campaigns_title: "📊 Gestione Campagne (v1.1)",
      kb_feature_organize: "Organizza con nomi, tag e note",
      kb_feature_status: "Traccia stato (Bozza, Pianificata, Inviata)",
      kb_feature_search: "Cerca e filtra campagne",
      kb_feature_duplicate: "Duplica campagne di successo",
      kb_quickstart_title: "Avvio Rapido",
      kb_quickstart_desc: "Inizia in pochi minuti con questi semplici passaggi:",
      kb_quickstart_step1: "Posiziona EmailCampaignManager.exe in una cartella qualsiasi e fai doppio clic",
      kb_quickstart_step2: "Il browser si apre automaticamente su http://localhost:5000",
      kb_quickstart_step3: "Consenti tramite antivirus se richiesto (le app PyInstaller possono attivare falsi positivi)",
      kb_quickstart_step4: "Configura le impostazioni SMTP",
      kb_quickstart_step5: "Importa il tuo CSV con i contatti",
      kb_quickstart_step6: "Crea la tua prima campagna e invia!",
      kb_campaigns_section_title: "Gestione Campagne",
      kb_campaigns_desc: "Gestisci tutte le tue campagne email in un unico posto organizzato.",
      kb_campaigns_create_title: "Crea una Campagna",
      kb_campaigns_create_step1: "Fai clic sulla scheda Campagne",
      kb_campaigns_create_step2: "Fai clic su ➕ Nuova Campagna",
      kb_campaigns_create_step3: "Componi la tua email nella scheda Componi",
      kb_campaigns_create_step4: "Fai clic su ⚙️ Impostazioni per impostare nome, tag e note",
      kb_campaigns_create_step5: "Fai clic su 💾 Salva per salvare i progressi",
      kb_campaigns_manage_title: "Gestisci Campagne",
      kb_campaigns_search: "Cerca: Digita nella casella di ricerca per trovare campagne",
      kb_campaigns_filter: "Filtra: Fai clic su Bozza/Pianificata/Inviata per filtrare per stato",
      kb_campaigns_edit: "Modifica: Fai clic su una scheda campagna per aprirla e modificarla",
      kb_campaigns_actions: "Azioni: Fai clic su ⋮ per opzioni Duplica o Elimina",
      kb_campaigns_send_title: "Invia una Campagna",
      kb_campaigns_send_step1: "Seleziona o crea una campagna",
      kb_campaigns_send_step2: "Carica il tuo file CSV con i destinatari",
      kb_campaigns_send_step3: "Configura le impostazioni SMTP",
      kb_campaigns_send_step4: "Fai clic su 🚀 Invia Email",
      kb_campaigns_send_step5: "Le statistiche si aggiornano automaticamente!",
      kb_templates_section_title: "Uso dei Template",
      kb_templates_desc: "Crea template email potenti e riutilizzabili con variabili e contenuto condizionale.",
      kb_templates_create_title: "Crea un Template",
      kb_templates_create_step1: "Fai clic sulla scheda Template",
      kb_templates_create_step2: "Fai clic su ➕ Nuovo Template",
      kb_templates_create_step3: "Inserisci nome e descrizione del template",
      kb_templates_create_step4: "Scrivi la tua email usando variabili e condizioni",
      kb_templates_create_step5: "Seleziona una categoria (promo, newsletter, cold, follow-up)",
      kb_templates_create_step6: "Fai clic su 💾 Salva Template",
      kb_templates_use_title: "Usa un Template",
      kb_templates_use_step1: "Nella scheda Componi, fai clic su 📄 Carica Template",
      kb_templates_use_step2: "Seleziona un template dalla libreria",
      kb_templates_use_step3: "L'oggetto e il corpo vengono compilati automaticamente",
      kb_templates_use_step4: "Le variabili saranno sostituite con dati reali dal tuo CSV",
      kb_templates_syntax_title: "Sintassi Template",
      kb_templates_syntax_vars: "Variabili: Usa qualsiasi colonna del tuo CSV con {{nome_colonna}}",
      kb_templates_syntax_conditions: "Condizioni: Mostra/nascondi contenuto basato sui dati",
      kb_templates_syntax_preview: "Anteprima: Fai clic sul pulsante anteprima per vedere come viene renderizzato con dati di esempio",
      kb_abtesting_section_title: "Esecuzione Test A/B",
      kb_abtesting_desc: "Testa diverse varianti di email per scoprire cosa funziona meglio per il tuo pubblico.",
      kb_abtesting_setup_title: "Configura un Test A/B",
      kb_abtesting_setup_step1: "Crea o modifica una campagna",
      kb_abtesting_setup_step2: "Fai clic su ⚙️ Impostazioni",
      kb_abtesting_setup_step3: "Abilita Modalità Test A/B",
      kb_abtesting_setup_step4: "Imposta il rapporto di divisione (predefinito 50/50)",
      kb_abtesting_setup_step5: "Vai alla scheda Componi",
      kb_abtesting_setup_step6: "Inserisci oggetto e corpo Variante A",
      kb_abtesting_setup_step7: "Inserisci oggetto e corpo Variante B",
      kb_abtesting_setup_step8: "Fai clic su 👁️ Anteprima per confrontare affiancate",
      kb_abtesting_send_title: "Invia Test A/B",
      kb_abtesting_send_step1: "Carica il tuo CSV con i destinatari",
      kb_abtesting_send_step2: "Configura le impostazioni SMTP",
      kb_abtesting_send_step3: "Fai clic su 🚀 Invia Test A/B",
      kb_abtesting_send_step4: "I destinatari vengono divisi automaticamente (es. 50% riceve A, 50% riceve B)",
      kb_abtesting_send_step5: "Visualizza statistiche separate per ciascuna variante",
      kb_scheduling_section_title: "Pianificazione Campagne",
      kb_scheduling_desc: "Pianifica campagne per invio futuro e controlla la velocità di invio.",
      kb_scheduling_schedule_title: "Pianifica per Dopo",
      kb_scheduling_schedule_step1: "Crea o modifica una campagna",
      kb_scheduling_schedule_step2: "Fai clic su ⚙️ Impostazioni",
      kb_scheduling_schedule_step3: "Imposta Data e Ora Pianificata",
      kb_scheduling_schedule_step4: "Seleziona il tuo Fuso Orario",
      kb_scheduling_schedule_step5: "Fai clic su 💾 Salva",
      kb_scheduling_schedule_step6: "La campagna mostra il badge ⏰ e verrà inviata automaticamente",
      kb_scheduling_ratelimit_title: "Controlla Velocità Invio",
      kb_scheduling_ratelimit_step1: "Nelle Impostazioni Campagna, regola lo slider Email al Minuto",
      kb_scheduling_ratelimit_step2: "Imposta a 0 per velocità massima (nessun limite)",
      kb_scheduling_ratelimit_step3: "Imposta da 1 a 60 per controllare la velocità di consegna",
      kb_scheduling_ratelimit_step4: "Aiuta a migliorare la deliverability ed evitare limiti di velocità",
      kb_scheduling_pause_title: "Pausa & Riprendi",
      kb_scheduling_pause_step1: "Durante l'invio, fai clic su ⏸️ Pausa se necessario",
      kb_scheduling_pause_step2: "Lo stato della campagna viene salvato automaticamente",
      kb_scheduling_pause_step3: "Fai clic su ▶️ Riprendi per continuare da dove si è fermata",
      kb_scheduling_pause_step4: "Se l'app si blocca, le campagne riprendono automaticamente al riavvio",
      kb_contacts_title: "Importa i tuoi Contatti",
      kb_contacts_desc: "Usa il TemplateCSV.csv incluso come punto di partenza.",
      kb_contacts_format_title: "Formato CSV",
      kb_contacts_headers: "Intestazioni richieste (esattamente): Name,Email separate da virgole",
      kb_contacts_encoding: "Salva con codifica UTF-8",
      kb_contacts_example_title: "Esempio",
      kb_contacts_empty_note: "Lascia Name vuoto se non ce l'hai (verrà usato il saluto predefinito)",
      kb_smtp_title: "Connetti il tuo Account Email",
      kb_smtp_desc: "Configura le impostazioni SMTP per inviare email.",
      kb_smtp_providers_title: "Provider Supportati",
      kb_smtp_gmail: "Gmail (usa App Password con 2FA abilitata)",
      kb_smtp_outlook: "Outlook/Hotmail",
      kb_smtp_yahoo: "Yahoo",
      kb_smtp_office365: "Office 365",
      kb_smtp_custom: "SMTP Personalizzato (qualsiasi provider)",
      kb_smtp_setup_title: "Passaggi di Configurazione",
      kb_smtp_step1: "Scegli il tuo provider dal menu a tendina",
      kb_smtp_step2: "Inserisci la tua email e password (o app password)",
      kb_smtp_step3: "Fai clic su Test Connessione",
      kb_smtp_step4: "In caso di successo, la password viene memorizzata in modo sicuro nel keychain di sistema",
      kb_smtp_step5: "Usa il menu a tendina per richiamare account salvati",
      kb_compose_title: "Componi il tuo Messaggio",
      kb_compose_desc: "Crea email personalizzate con variabili e template.",
      kb_compose_basics_title: "Nozioni di Base",
      kb_compose_subject: "L'oggetto è obbligatorio",
      kb_compose_mode: "Passa tra modalità Testo e HTML nell'editor",
      kb_compose_attachments: "Aggiungi allegati condivisi con Carica File",
      kb_compose_variables_title: "Uso delle Variabili",
      kb_compose_jinja: "Sintassi Jinja2: {{first_name}}, {{email}}, {{company}}, o qualsiasi colonna CSV",
      kb_compose_legacy: "Sintassi legacy: {name} e {email} ancora supportati",
      kb_compose_conditions: "Condizioni: {% if company %}presso {{company}}{% endif %} mostra contenuto solo se il campo esiste",
      kb_compose_default: "Se Name manca, viene usato il Saluto Predefinito (es. \"Gentile Amico\")",
      kb_compose_templates_title: "Carica Template",
      kb_compose_templates_desc: "Fai clic su 📄 Carica Template dalla scheda Template per riutilizzare i tuoi messaggi migliori.",
      kb_send_title: "Invia la tua Campagna",
      kb_send_desc: "Invia la tua campagna email e monitora i progressi in tempo reale.",
      kb_send_steps_title: "Passaggi",
      kb_send_step1: "Premi 🚀 Invia Email",
      kb_send_step2: "Guarda log in tempo reale, barra di avanzamento e statistiche mentre la campagna è in esecuzione",
      kb_send_step3: "Lo stato della campagna si aggiorna automaticamente",
      kb_send_monitoring_title: "Monitoraggio",
      kb_send_progress: "Barra di avanzamento in tempo reale",
      kb_send_logs: "Log in tempo reale che mostrano ogni email inviata",
      kb_send_stats: "Statistiche successo/errore",
      kb_send_pause_option: "Opzione per mettere in pausa durante l'invio",
      kb_security_title: "Sicurezza",
      kb_security_desc: "I tuoi dati e credenziali sono protetti.",
      kb_security_features_title: "Funzionalità di Sicurezza",
      kb_security_keychain: "Password memorizzate localmente nel keychain di sistema (Gestione Credenziali Windows)",
      kb_security_local: "Tutti i dati rimangono sul tuo computer - nessuna archiviazione cloud",
      kb_security_sqlite: "Database SQLite per archiviazione campagne",
      kb_security_remove_title: "Rimuovi Credenziali",
      kb_security_remove_desc: "Per rimuovere le credenziali memorizzate: seleziona l'account e fai clic su Annulla Account.",
      kb_troubleshooting_title: "Risoluzione Problemi",
      kb_troubleshooting_common_title: "Problemi Comuni",
      kb_trouble_smtp_title: "Connessione SMTP Fallita",
      kb_trouble_smtp_1: "Usa una App Password (Gmail richiede 2FA + App Password)",
      kb_trouble_smtp_2: "Verifica host/porta per SMTP Personalizzato",
      kb_trouble_smtp_3: "Controlla la tua connessione internet",
      kb_trouble_csv_title: "CSV Rifiutato",
      kb_trouble_csv_1: "Le intestazioni devono essere esattamente Name,Email",
      kb_trouble_csv_2: "Usa separatore virgola (no punto e virgola)",
      kb_trouble_csv_3: "Salva con codifica UTF-8",
      kb_trouble_attachments_title: "Allegati Corrotti",
      kb_trouble_attachments_1: "Tutti i tipi di file supportati (PDF, DOCX, immagini, ecc.)",
      kb_trouble_attachments_2: "I file sono codificati automaticamente come base64",
      kb_trouble_attachments_3: "Controlla le impostazioni del client email del destinatario",
      kb_trouble_icon_title: "Icona Windows Sembra Vecchia",
      kb_trouble_icon_desc: "Elimina o rinomina il vecchio EmailCampaignManager.exe e copia il nuovo (Windows potrebbe memorizzare le icone nella cache).",
      kb_support_title: "Supporto & Contatti",
      kb_support_desc: "Hai bisogno di aiuto, domande o vuoi solo salutare? 😊",
      kb_support_contact_title: "Contattami",
      kb_support_contact_desc: "Fai clic sul pulsante qui sotto per contattarmi:",
      kb_support_contact_btn: "Contattami"
    }
  };

  // Funzione per rilevare la lingua del browser
  function detectBrowserLanguage() {
    const browserLang = navigator.language || navigator.userLanguage;
    // Estrai il codice lingua (es. "it-IT" -> "it", "en-US" -> "en")
    const langCode = browserLang.split('-')[0].toLowerCase();
    
    // Verifica se la lingua è supportata, altrimenti usa inglese come fallback
    if (translations[langCode]) {
      return langCode;
    }
    return 'en'; // Default fallback
  }

  // Funzione per cambiare lingua
  function setLang(lang) {
    document.documentElement.lang = lang;

    // Aggiorna testi
    document.querySelectorAll("[data-key]").forEach(el => {
      const key = el.dataset.key;
      if (translations[lang] && translations[lang][key]) {
        el.textContent = translations[lang][key];
      }
    });

    // Aggiorna pulsanti lingua
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem("kb_lang", lang);
  }

  // Funzione per navigare tra le sezioni
  function showSection(sectionId) {
    // Nascondi tutte le sezioni
    document.querySelectorAll('.kb-section').forEach(section => {
      section.classList.remove('active');
    });

    // Mostra la sezione richiesta
    const targetSection = document.getElementById(`section-${sectionId}`);
    if (targetSection) {
      targetSection.classList.add('active');
    } else {
      console.warn(`Section ${sectionId} not found`);
    }

    // Aggiorna link sidebar
    document.querySelectorAll('.kb-nav-link').forEach(link => {
      link.classList.toggle('active', link.dataset.section === sectionId);
    });
  }

  // Gestione click sidebar
  document.querySelectorAll('.kb-nav-link').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const section = link.dataset.section;
      if (section) {
        showSection(section);
      }
    });
  });

  // Gestione click pulsanti lingua
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const lang = btn.dataset.lang;
      if (lang) {
        setLang(lang);
      }
    });
  });

  // Lingua iniziale: prima controlla localStorage, poi rileva dal browser
  const savedLang = localStorage.getItem("kb_lang");
  const initialLang = savedLang || detectBrowserLanguage();
  setLang(initialLang);

  // Mostra la prima sezione come predefinita
  showSection('intro');
});
